services:
  db:
    image: postgres:15-alpine    # Vers√£o otimizada que reflete o ambiente do Supabase
    container_name: mergeskills-db
    restart: unless-stopped
    ports:
      - "5432:5432"              # Mapeia Porta PC:Porta Container
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: mergeskills
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: